application: catbirdstats
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# - url: /load/.*
#   script: catbirdload.app
- url: /.*
  script: catbirdstats.app


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"

builtins:
- appstats: on

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*